Draft - Update task count
ONSdigital/dp-search-data-finder pull request #12
Opened 2022-03-24 16:24 UTC by bpathak-ons

### What

* Callback to Search Reindex API to update task counts

### How to review

* code sense check
* CI pass

### Who can review

* anyone

2022-04-14 15:59 UTC, rahulPalliyalil requested changes

2022-04-19 08:05 UTC, bpathak-ons commented on handler/handler.go
> +	payload := []byte(task)
yes, it will be called with new value of task and number of document

2022-04-19 08:10 UTC, bpathak-ons commented on handler/handler.go
> +	}
I tried this was causing lint error (govet)

2022-04-19 08:42 UTC, rahulPalliyalil commented on handler/handler.go
> +	}
what is the error ? @bpathak-ons

2022-04-19 09:22 UTC, bpathak-ons commented on handler/handler.go
> +	}
now addressed as unused task is now removed

2022-04-19 09:35 UTC, rahulPalliyalil approved these changes

2022-04-19 09:37 UTC, merged